### ISSUE TITLE
Style Backstage to match CNCF Landscape's theme

### ISSUE THREAD

**Issue by minkimcello** [minkimcello/landscape3#8]
- Use [backstage theme](https://backstage.io/docs/getting-started/app-custom-theme) to modify colours to match [landscape2](https://cncf.landscape2.io/)
- Replace side nav bar logo with the [cloud native landscape logo](https://github.com/cncf/landscape/blob/master/images/left-logo.svg)

**Comment by aq1e** [comment]
🫡
